/* ARCHIVO: 00_init_user.sql
   Ronny Mendez
*/

-- 1. Crear el usuario (Schema)
CREATE USER CONTROL_ASISTENCIA IDENTIFIED BY "ControlAsistencia123";

-- 2. Asignar Quota (Espacio en disco)
ALTER USER CONTROL_ASISTENCIA QUOTA UNLIMITED ON DATA;

-- 3. Conceder Permisos (Grant)
GRANT CREATE SESSION TO CONTROL_ASISTENCIA;
GRANT CREATE TABLE TO CONTROL_ASISTENCIA;
GRANT CREATE SEQUENCE TO CONTROL_ASISTENCIA;
GRANT CREATE PROCEDURE TO CONTROL_ASISTENCIA;
GRANT CREATE TRIGGER TO CONTROL_ASISTENCIA;
GRANT CREATE VIEW TO CONTROL_ASISTENCIA;
GRANT CREATE JOB TO CONTROL_ASISTENCIA;

-- Permiso para ejecutar Jobs programados
GRANT EXECUTE ON DBMS_SCHEDULER TO CONTROL_ASISTENCIA;
