/* ⚠️ SLYTHERIN PROTOCOL: CLEAN SLATE
   Borra todo para reconstruir desde cero.
*/
PROMPT === INICIANDO LIMPIEZA TOTAL DEL ESQUEMA ===

-- Tablas Transaccionales
DROP TABLE LOG_SEGURIDAD CASCADE CONSTRAINTS;
DROP TABLE LOG_JUSTIFICACION CASCADE CONSTRAINTS;
DROP TABLE LOG_ASISTENCIA CASCADE CONSTRAINTS;
DROP TABLE JUSTIFICACION CASCADE CONSTRAINTS;
DROP TABLE ASISTENCIA CASCADE CONSTRAINTS;
DROP TABLE CONFIGURACION CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

-- Secuencias
DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_ASISTENCIA;
DROP SEQUENCE SEQ_JUSTIFICACION;
DROP SEQUENCE SEQ_LOG_ASIS;
DROP SEQUENCE SEQ_LOG_JUST;
DROP SEQUENCE SEQ_LOG_SEG;

PROMPT === LIMPIEZA COMPLETADA ===